# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: darisxchen@gmail.com
author_name: custom-widget
has_binder: true
has_settings: false
kind: frontend
labextension_name: custom-widget
project_short_description: A JupyterLab extension.
python_name: custom_widget
repository: git@github.com:SecretCastle/jupyter-custom-widget.git
test: true

